-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.admin_impersonation_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  superadmin_id uuid NOT NULL,
  impersonated_user_id uuid NOT NULL,
  action text NOT NULL CHECK (action = ANY (ARRAY['start'::text, 'end'::text])),
  ip_address text,
  user_agent text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT admin_impersonation_logs_pkey PRIMARY KEY (id),
  CONSTRAINT admin_impersonation_logs_superadmin_id_fkey FOREIGN KEY (superadmin_id) REFERENCES auth.users(id),
  CONSTRAINT admin_impersonation_logs_impersonated_user_id_fkey FOREIGN KEY (impersonated_user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.admin_page_permissions (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  admin_user_id uuid NOT NULL,
  page_path text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT admin_page_permissions_pkey PRIMARY KEY (id),
  CONSTRAINT admin_page_permissions_admin_user_id_fkey FOREIGN KEY (admin_user_id) REFERENCES public.business_info(id)
);
CREATE TABLE public.admin_page_permissions_v2 (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  admin_user_id uuid NOT NULL UNIQUE,
  page_paths jsonb NOT NULL DEFAULT '[]'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT admin_page_permissions_v2_pkey PRIMARY KEY (id),
  CONSTRAINT admin_page_permissions_v2_admin_user_id_fkey FOREIGN KEY (admin_user_id) REFERENCES public.business_info(id)
);
CREATE TABLE public.ai_instructions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title text NOT NULL,
  content text NOT NULL,
  instruction_type text NOT NULL CHECK (instruction_type = ANY (ARRAY['loom'::text, 'text'::text, 'pdf'::text, 'sheet'::text, 'url'::text, 'document'::text])),
  role_access text NOT NULL DEFAULT 'both'::text CHECK (role_access = ANY (ARRAY['admin'::text, 'user'::text, 'all'::text])),
  category text NOT NULL DEFAULT 'other'::text CHECK (category = ANY (ARRAY['company_info'::text, 'product_info'::text, 'service_info'::text, 'other'::text])),
  url text,
  document_url text,
  document_name text,
  extraction_metadata jsonb,
  vector_embedding USER-DEFINED,
  embedding_updated_at timestamp with time zone,
  is_active boolean DEFAULT true,
  priority integer DEFAULT 0,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT ai_instructions_pkey PRIMARY KEY (id),
  CONSTRAINT ai_instructions_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.ai_onboarding_questions (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL UNIQUE,
  questions_data jsonb NOT NULL,
  is_completed boolean NOT NULL DEFAULT false,
  completed_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT ai_onboarding_questions_pkey PRIMARY KEY (id),
  CONSTRAINT ai_onboarding_questions_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.app_cache (
  id integer NOT NULL DEFAULT nextval('app_cache_id_seq'::regclass),
  cache_key character varying NOT NULL UNIQUE,
  user_id uuid,
  cache_type character varying NOT NULL,
  data jsonb NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  expires_at timestamp with time zone NOT NULL,
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT app_cache_pkey PRIMARY KEY (id),
  CONSTRAINT app_cache_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.bank_holidays (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  holiday_name text NOT NULL,
  holiday_date date NOT NULL,
  year integer NOT NULL,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  team_id uuid,
  CONSTRAINT bank_holidays_pkey PRIMARY KEY (id),
  CONSTRAINT bank_holidays_team_id_fkey FOREIGN KEY (team_id) REFERENCES auth.users(id)
);
CREATE TABLE public.battle_plan (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  businessplanlink text DEFAULT ''::text,
  missionstatement text DEFAULT ''::text,
  visionstatement text DEFAULT ''::text,
  purposewhy ARRAY DEFAULT '{}'::jsonb[],
  strategicanchors ARRAY DEFAULT '{}'::jsonb[],
  corevalues ARRAY DEFAULT '{}'::jsonb[],
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  business_plan_content text DEFAULT ''::text,
  oneyeartarget jsonb,
  tenyeartarget jsonb,
  fiveyeartarget ARRAY DEFAULT '{}'::jsonb[],
  static_questions_answers jsonb DEFAULT '{"answers": {}, "questions": []}'::jsonb,
  CONSTRAINT battle_plan_pkey PRIMARY KEY (id),
  CONSTRAINT battle_plan_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.business_info (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid UNIQUE,
  full_name text NOT NULL,
  business_name text NOT NULL,
  email text NOT NULL,
  phone_number text NOT NULL,
  payment_option text NOT NULL,
  payment_remaining numeric DEFAULT 0,
  command_hq_link text,
  command_hq_created boolean DEFAULT false,
  gd_folder_created boolean DEFAULT false,
  meeting_scheduled boolean DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  profile_picture_url text,
  role text NOT NULL DEFAULT 'user'::text CHECK (role = ANY (ARRAY['super_admin'::text, 'admin'::text, 'user'::text])),
  google_review_link text,
  team_id uuid,
  permissions jsonb,
  job_title text DEFAULT ''::text,
  manager text DEFAULT ''::text,
  critical_accountabilities ARRAY DEFAULT '{}'::jsonb[],
  playbooks_owned ARRAY DEFAULT '{}'::jsonb[],
  department text DEFAULT ''::text,
  manager_id uuid,
  department_id uuid,
  wbt_onboarding text DEFAULT ''::text,
  CONSTRAINT business_info_pkey PRIMARY KEY (id),
  CONSTRAINT business_info_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT business_info_team_id_fkey FOREIGN KEY (team_id) REFERENCES auth.users(id),
  CONSTRAINT business_info_manager_id_fkey FOREIGN KEY (manager_id) REFERENCES public.business_info(id),
  CONSTRAINT business_info_department_id_fkey FOREIGN KEY (department_id) REFERENCES public.departments(id)
);
CREATE TABLE public.business_owner_instructions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  title text NOT NULL,
  content text NOT NULL,
  content_type text NOT NULL DEFAULT 'text'::text CHECK (content_type = ANY (ARRAY['text'::text, 'pdf'::text, 'doc'::text, 'link'::text, 'loom'::text])),
  url text,
  extraction_metadata jsonb,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  embeddings USER-DEFINED,
  CONSTRAINT business_owner_instructions_pkey PRIMARY KEY (id),
  CONSTRAINT business_owner_instructions_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.chain_of_command (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  name text DEFAULT ''::text,
  manager text DEFAULT ''::text,
  jobtitle text DEFAULT ''::text,
  criticalaccountabilities ARRAY DEFAULT '{}'::jsonb[],
  playbooksowned ARRAY DEFAULT '{}'::jsonb[],
  department text DEFAULT ''::text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT chain_of_command_pkey PRIMARY KEY (id),
  CONSTRAINT chain_of_command_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.chat_history (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  messages jsonb NOT NULL DEFAULT '[]'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  title text NOT NULL DEFAULT 'New Chat'::text,
  document_ids ARRAY,
  pinned boolean,
  group_type text DEFAULT 'innovation'::text CHECK (group_type = ANY (ARRAY['general'::text, 'innovation'::text, 'operations'::text, 'growth'::text, 'financials'::text, 'competitors'::text, 'business-foundations'::text])),
  CONSTRAINT chat_history_pkey PRIMARY KEY (id),
  CONSTRAINT chat_history_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.chat_ideas (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  title text NOT NULL,
  summary text NOT NULL,
  original_chat_id uuid NOT NULL,
  original_messages jsonb NOT NULL DEFAULT '[]'::jsonb,
  tags ARRAY DEFAULT ARRAY[]::text[],
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT chat_ideas_pkey PRIMARY KEY (id),
  CONSTRAINT chat_ideas_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT chat_ideas_original_chat_id_fkey FOREIGN KEY (original_chat_id) REFERENCES public.chat_history(id)
);
CREATE TABLE public.chat_messages (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  user_id uuid,
  session_id uuid DEFAULT gen_random_uuid(),
  role text NOT NULL CHECK (role = ANY (ARRAY['user'::text, 'assistant'::text])),
  content text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  metadata jsonb,
  CONSTRAINT chat_messages_pkey PRIMARY KEY (id),
  CONSTRAINT chat_messages_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.chatbot_flow_node_links (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  chatbot_id uuid NOT NULL,
  order_index integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  node_key text NOT NULL,
  settings jsonb NOT NULL DEFAULT '{}'::jsonb,
  CONSTRAINT chatbot_flow_node_links_pkey PRIMARY KEY (id),
  CONSTRAINT chatbot_flow_node_links_chatbot_id_fkey FOREIGN KEY (chatbot_id) REFERENCES public.chatbots(id)
);
CREATE TABLE public.chatbot_instructions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title text NOT NULL,
  content text NOT NULL,
  content_type text NOT NULL CHECK (content_type = ANY (ARRAY['text'::text, 'pdf'::text, 'doc'::text, 'link'::text, 'youtube'::text, 'loom'::text, 'vimeo'::text, 'faq'::text])),
  url text,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  created_by uuid,
  extraction_metadata jsonb DEFAULT '{}'::jsonb,
  is_active boolean NOT NULL DEFAULT true,
  priority integer DEFAULT 0,
  embedding USER-DEFINED,
  embedding_updated_at timestamp with time zone,
  category USER-DEFINED DEFAULT 'uncategorized'::instruction_category,
  CONSTRAINT chatbot_instructions_pkey PRIMARY KEY (id),
  CONSTRAINT chatbot_instructions_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.chatbots (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  base_prompt text NOT NULL DEFAULT ''::text,
  is_active boolean NOT NULL DEFAULT true,
  model_name text,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT chatbots_pkey PRIMARY KEY (id),
  CONSTRAINT chatbots_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.chq_benefits (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  benefit_name text NOT NULL,
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  iframe text,
  CONSTRAINT chq_benefits_pkey PRIMARY KEY (id)
);
CREATE TABLE public.chq_checklist (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  checklist_item text NOT NULL,
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT chq_checklist_pkey PRIMARY KEY (id)
);
CREATE TABLE public.chq_timeline (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  week_number integer NOT NULL,
  event_name text NOT NULL,
  scheduled_date date NOT NULL,
  duration_minutes integer,
  description text,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  meeting_link text,
  active boolean,
  CONSTRAINT chq_timeline_pkey PRIMARY KEY (id)
);
CREATE TABLE public.company_onboarding (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL UNIQUE,
  onboarding_data jsonb NOT NULL,
  completed boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  competitor_data jsonb,
  CONSTRAINT company_onboarding_pkey PRIMARY KEY (id),
  CONSTRAINT company_onboarding_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.conversations (
  session_id text NOT NULL,
  messages jsonb NOT NULL DEFAULT '[]'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT conversations_pkey PRIMARY KEY (session_id)
);
CREATE TABLE public.course_lessons (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  module_id uuid,
  title character varying NOT NULL,
  description text,
  video_url character varying,
  video_type character varying DEFAULT 'vimeo'::character varying,
  video_duration_seconds integer,
  order_index integer NOT NULL,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT course_lessons_pkey PRIMARY KEY (id),
  CONSTRAINT course_lessons_module_id_fkey FOREIGN KEY (module_id) REFERENCES public.course_modules(id)
);
CREATE TABLE public.course_modules (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  course_id uuid,
  title character varying NOT NULL,
  description text,
  order_index integer NOT NULL,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT course_modules_pkey PRIMARY KEY (id),
  CONSTRAINT course_modules_course_id_fkey FOREIGN KEY (course_id) REFERENCES public.courses(id)
);
CREATE TABLE public.courses (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title character varying NOT NULL,
  description text,
  thumbnail_url character varying,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT courses_pkey PRIMARY KEY (id)
);
CREATE TABLE public.departments (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name text NOT NULL,
  team_id uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT departments_pkey PRIMARY KEY (id)
);
CREATE TABLE public.document_history (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  document_id text NOT NULL,
  document_type text NOT NULL,
  content text NOT NULL,
  user_id uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT document_history_pkey PRIMARY KEY (id)
);
CREATE TABLE public.embedding_queue (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  instruction_id uuid NOT NULL,
  title text NOT NULL,
  content text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  processed_at timestamp with time zone,
  processing_attempts integer NOT NULL DEFAULT 0,
  error_message text,
  CONSTRAINT embedding_queue_pkey PRIMARY KEY (id),
  CONSTRAINT embedding_queue_instruction_id_fkey FOREIGN KEY (instruction_id) REFERENCES public.chatbot_instructions(id)
);
CREATE TABLE public.error_codes (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  code character varying NOT NULL UNIQUE,
  description text,
  severity character varying CHECK (severity::text = ANY (ARRAY['critical'::character varying, 'warning'::character varying, 'info'::character varying]::text[])),
  category character varying,
  troubleshooting_steps text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT error_codes_pkey PRIMARY KEY (id)
);
CREATE TABLE public.external_api_data (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  api_source text NOT NULL CHECK (api_source = ANY (ARRAY['google_analytics'::text, 'xero'::text, 'servicem8'::text, 'quickbooks'::text])),
  account_identifier text,
  account_name text,
  data_date date NOT NULL,
  fetched_at timestamp with time zone DEFAULT now(),
  raw_data jsonb NOT NULL DEFAULT '{}'::jsonb,
  metrics jsonb DEFAULT '{}'::jsonb,
  status text DEFAULT 'success'::text CHECK (status = ANY (ARRAY['success'::text, 'error'::text, 'partial'::text])),
  error_message text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT external_api_data_pkey PRIMARY KEY (id),
  CONSTRAINT external_api_data_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.finance_analysis (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  file_id uuid NOT NULL,
  user_id uuid NOT NULL,
  team_id uuid NOT NULL,
  analysis_result jsonb NOT NULL,
  summary text,
  status text DEFAULT 'completed'::text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  period_type text DEFAULT 'monthly'::text CHECK (period_type = ANY (ARRAY['monthly'::text, 'yearly'::text])),
  CONSTRAINT finance_analysis_pkey PRIMARY KEY (id),
  CONSTRAINT finance_analysis_file_id_fkey FOREIGN KEY (file_id) REFERENCES public.finance_files(id),
  CONSTRAINT finance_analysis_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.finance_files (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  team_id uuid NOT NULL,
  file_name text NOT NULL,
  file_type text NOT NULL,
  file_size bigint NOT NULL,
  file_url text NOT NULL,
  storage_path text NOT NULL,
  month text,
  year text NOT NULL,
  uploaded_by text NOT NULL,
  upload_date timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  extracted_text text,
  period_type text DEFAULT 'monthly'::text CHECK (period_type = ANY (ARRAY['monthly'::text, 'yearly'::text])),
  CONSTRAINT finance_files_pkey PRIMARY KEY (id),
  CONSTRAINT finance_files_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.ghl_appointments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  team_id uuid,
  ghl_appointment_id text NOT NULL UNIQUE,
  ghl_calendar_id text NOT NULL,
  ghl_contact_id text,
  title text,
  description text,
  start_time timestamp with time zone NOT NULL,
  end_time timestamp with time zone NOT NULL,
  status text,
  created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT ghl_appointments_pkey PRIMARY KEY (id),
  CONSTRAINT ghl_appointments_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.ghl_calendar_settings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  team_id uuid,
  ghl_calendar_id text NOT NULL,
  name text NOT NULL,
  description text,
  purpose text,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT ghl_calendar_settings_pkey PRIMARY KEY (id),
  CONSTRAINT ghl_calendar_settings_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.ghl_contacts_cache (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  team_id uuid,
  ghl_contact_id text NOT NULL,
  first_name text,
  last_name text,
  email text,
  phone text,
  contact_name text,
  type text DEFAULT 'lead'::text,
  source text,
  address1 text,
  city text,
  state text,
  country text,
  postal_code text,
  custom_fields jsonb DEFAULT '[]'::jsonb,
  tags ARRAY DEFAULT '{}'::text[],
  assigned_to text,
  date_added timestamp with time zone,
  last_synced_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT ghl_contacts_cache_pkey PRIMARY KEY (id),
  CONSTRAINT ghl_contacts_cache_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.ghl_field_mappings (
  mapping_id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  team_id uuid,
  mapping_name text NOT NULL,
  pipeline_id text,
  opportunity_stage text,
  field_mappings jsonb NOT NULL DEFAULT '{}'::jsonb,
  tags ARRAY DEFAULT '{}'::text[],
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT ghl_field_mappings_pkey PRIMARY KEY (mapping_id),
  CONSTRAINT ghl_field_mappings_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.ghl_integrations (
  integration_id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  team_id uuid,
  access_token text NOT NULL,
  refresh_token text NOT NULL,
  token_expires_at timestamp with time zone NOT NULL,
  company_id text NOT NULL,
  location_id text,
  user_type text NOT NULL CHECK (user_type = ANY (ARRAY['Company'::text, 'Location'::text])),
  scope text NOT NULL,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT ghl_integrations_pkey PRIMARY KEY (integration_id),
  CONSTRAINT ghl_integrations_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.global_services (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  service_name text NOT NULL UNIQUE,
  description text,
  category text,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  display_order integer NOT NULL DEFAULT 0,
  CONSTRAINT global_services_pkey PRIMARY KEY (id)
);
CREATE TABLE public.google_analytics_tokens (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid UNIQUE,
  access_token text NOT NULL,
  refresh_token text,
  expires_at timestamp with time zone,
  scope text,
  token_type text DEFAULT 'Bearer'::text,
  property_id text,
  account_name text,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  use_organization_default boolean DEFAULT true,
  use_shared boolean DEFAULT true,
  connection_type text DEFAULT 'own'::text CHECK (connection_type = ANY (ARRAY['own'::text, 'shared'::text])),
  CONSTRAINT google_analytics_tokens_pkey PRIMARY KEY (id),
  CONSTRAINT google_analytics_tokens_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.google_calendar_events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  google_event_id text NOT NULL,
  calendar_id text DEFAULT 'primary'::text,
  title text NOT NULL,
  description text,
  location text,
  start_time timestamp with time zone NOT NULL,
  end_time timestamp with time zone NOT NULL,
  all_day boolean DEFAULT false,
  timezone text,
  event_link text,
  attendees jsonb DEFAULT '[]'::jsonb,
  recurrence jsonb,
  status text DEFAULT 'confirmed'::text,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  last_synced_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT google_calendar_events_pkey PRIMARY KEY (id),
  CONSTRAINT google_calendar_events_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.google_calendar_tokens (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid UNIQUE,
  access_token text NOT NULL,
  refresh_token text,
  expires_at timestamp with time zone,
  scope text,
  token_type text DEFAULT 'Bearer'::text,
  calendar_id text DEFAULT 'primary'::text,
  account_name text,
  sync_token text,
  last_sync_at timestamp with time zone,
  sync_status text DEFAULT 'pending'::text CHECK (sync_status = ANY (ARRAY['pending'::text, 'syncing'::text, 'completed'::text, 'error'::text])),
  error_message text,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT google_calendar_tokens_pkey PRIMARY KEY (id),
  CONSTRAINT google_calendar_tokens_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.hwgt_plan (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid,
  howwegetthereplan jsonb NOT NULL DEFAULT '{"modelBrand": {"Q0": "", "Q4": "", "Q8": "", "Q12": ""}, "customerAvatars": {"Q0": "", "Q4": "", "Q8": "", "Q12": ""}, "productsServices": {"Q0": "", "Q4": "", "Q8": "", "Q12": ""}, "teamOrganisation": {"Q0": "", "Q4": "", "Q8": "", "Q12": ""}, "customerAcquisition": {"Q0": "", "Q4": "", "Q8": "", "Q12": ""}, "fulfillmentProduction": {"Q0": "", "Q4": "", "Q8": "", "Q12": ""}}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT hwgt_plan_pkey PRIMARY KEY (id),
  CONSTRAINT hwgt_plan_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.innovation_chat_history (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  title text NOT NULL DEFAULT 'New Innovation'::text,
  messages jsonb NOT NULL DEFAULT '[]'::jsonb,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT innovation_chat_history_pkey PRIMARY KEY (id),
  CONSTRAINT innovation_chat_history_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.innovation_chat_training_data (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  original_chat_id uuid NOT NULL,
  user_id uuid NOT NULL,
  title text NOT NULL,
  messages jsonb NOT NULL,
  session_metadata jsonb DEFAULT '{}'::jsonb,
  archived_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  archive_reason text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT innovation_chat_training_data_pkey PRIMARY KEY (id),
  CONSTRAINT innovation_chat_training_data_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.innovation_documents (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  title text NOT NULL,
  file_name text NOT NULL,
  file_type text NOT NULL,
  file_size bigint NOT NULL,
  upload_status text NOT NULL DEFAULT 'processing'::text CHECK (upload_status = ANY (ARRAY['uploading'::text, 'processing'::text, 'completed'::text, 'error'::text])),
  extracted_content text,
  file_url text,
  extraction_metadata jsonb,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT innovation_documents_pkey PRIMARY KEY (id),
  CONSTRAINT innovation_documents_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.key_initiative_departments (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  key_initiative_id uuid NOT NULL,
  department_id uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT key_initiative_departments_pkey PRIMARY KEY (id),
  CONSTRAINT key_initiative_departments_key_initiative_id_fkey FOREIGN KEY (key_initiative_id) REFERENCES public.key_initiatives(id),
  CONSTRAINT key_initiative_departments_department_id_fkey FOREIGN KEY (department_id) REFERENCES public.departments(id)
);
CREATE TABLE public.key_initiatives (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name text NOT NULL,
  status text NOT NULL DEFAULT 'Backlog'::text CHECK (status = ANY (ARRAY['Backlog'::text, 'In Progress'::text, 'On Track'::text, 'Behind'::text, 'Completed'::text])),
  owner_id uuid,
  stakeholders ARRAY,
  due_date date,
  results text,
  associated_playbook_id uuid,
  team_id uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT key_initiatives_pkey PRIMARY KEY (id),
  CONSTRAINT key_initiatives_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES public.business_info(id),
  CONSTRAINT key_initiatives_associated_playbook_id_fkey FOREIGN KEY (associated_playbook_id) REFERENCES public.playbooks(id)
);
CREATE TABLE public.leave_approvals (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  leave_id uuid NOT NULL,
  approver_id uuid NOT NULL,
  action text NOT NULL CHECK (action = ANY (ARRAY['approved'::text, 'rejected'::text])),
  comments text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT leave_approvals_pkey PRIMARY KEY (id),
  CONSTRAINT leave_approvals_leave_id_fkey FOREIGN KEY (leave_id) REFERENCES public.team_leaves(id),
  CONSTRAINT leave_approvals_approver_id_fkey FOREIGN KEY (approver_id) REFERENCES auth.users(id)
);
CREATE TABLE public.leave_entitlements (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  team_id uuid NOT NULL,
  total_entitlement_days integer NOT NULL DEFAULT 25,
  year integer NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT leave_entitlements_pkey PRIMARY KEY (id),
  CONSTRAINT leave_entitlements_team_id_fkey FOREIGN KEY (team_id) REFERENCES auth.users(id)
);
CREATE TABLE public.machines (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  enginename text NOT NULL,
  enginetype text NOT NULL CHECK (enginetype = ANY (ARRAY['GROWTH'::text, 'FULFILLMENT'::text, 'INNOVATION'::text])),
  description text,
  triggeringevents ARRAY DEFAULT ARRAY[]::jsonb[],
  endingevent ARRAY DEFAULT ARRAY[]::jsonb[],
  actionsactivities ARRAY DEFAULT ARRAY[]::jsonb[],
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  figma_link text,
  figma_embed text,
  image_url text,
  image_urls text,
  welcome_completed boolean NOT NULL DEFAULT false,
  questions jsonb,
  answers jsonb,
  questions_completed boolean NOT NULL DEFAULT false,
  ai_assisted boolean NOT NULL DEFAULT false,
  service_name text DEFAULT 'default'::text,
  service_id uuid,
  subcategory_id uuid,
  team_service_id uuid,
  CONSTRAINT machines_pkey PRIMARY KEY (id),
  CONSTRAINT machines_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT machines_subcategory_id_fkey FOREIGN KEY (subcategory_id) REFERENCES public.service_subcategories(id),
  CONSTRAINT machines_service_id_fkey FOREIGN KEY (service_id) REFERENCES public.global_services(id),
  CONSTRAINT machines_team_service_id_fkey FOREIGN KEY (team_service_id) REFERENCES public.team_services(id)
);
CREATE TABLE public.meeting_rhythm_planner (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  meeting_type text NOT NULL,
  meeting_date date NOT NULL,
  meeting_title text NOT NULL DEFAULT ''::text,
  meeting_description text DEFAULT ''::text,
  meeting_color text DEFAULT ''::text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT meeting_rhythm_planner_pkey PRIMARY KEY (id),
  CONSTRAINT meeting_rhythm_planner_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.onboarding_feedback (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  feedback_text text NOT NULL,
  rating integer CHECK (rating IS NULL OR rating >= 1 AND rating <= 5),
  feedback_type text DEFAULT 'general'::text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT onboarding_feedback_pkey PRIMARY KEY (id),
  CONSTRAINT onboarding_feedback_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.performance_kpis (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  session_id uuid NOT NULL UNIQUE,
  revenue numeric DEFAULT 0,
  revenue_status text DEFAULT 'todo'::text,
  ad_spend numeric DEFAULT 0,
  ad_spend_status text DEFAULT 'todo'::text,
  leads numeric DEFAULT 0,
  leads_status text DEFAULT 'todo'::text,
  surveys_booked numeric DEFAULT 0,
  surveys_booked_status text DEFAULT 'todo'::text,
  jobs_completed numeric DEFAULT 0,
  jobs_completed_status text DEFAULT 'todo'::text,
  avg_cost_per_lead numeric DEFAULT 0,
  avg_cost_per_lead_status text DEFAULT 'todo'::text,
  avg_cost_per_job numeric DEFAULT 0,
  avg_cost_per_job_status text DEFAULT 'todo'::text,
  lead_to_survey_rate numeric DEFAULT 0,
  lead_to_survey_rate_status text DEFAULT 'todo'::text,
  survey_to_job_rate numeric DEFAULT 0,
  survey_to_job_rate_status text DEFAULT 'todo'::text,
  lead_to_job_rate numeric DEFAULT 0,
  lead_to_job_rate_status text DEFAULT 'todo'::text,
  roas numeric DEFAULT 0,
  roas_status text DEFAULT 'todo'::text,
  roi_pounds numeric DEFAULT 0,
  roi_pounds_status text DEFAULT 'todo'::text,
  roi_percent numeric DEFAULT 0,
  roi_percent_status text DEFAULT 'todo'::text,
  google_reviews numeric DEFAULT 0,
  google_reviews_status text DEFAULT 'todo'::text,
  review_rating numeric DEFAULT 0,
  review_rating_status text DEFAULT 'todo'::text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT performance_kpis_pkey PRIMARY KEY (id),
  CONSTRAINT performance_kpis_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.performance_sessions(id)
);
CREATE TABLE public.performance_sessions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  team_id uuid,
  month text NOT NULL,
  year integer NOT NULL,
  date_of_call date,
  attendance jsonb DEFAULT '[]'::jsonb,
  achievements jsonb DEFAULT '[]'::jsonb,
  challenges jsonb DEFAULT '[]'::jsonb,
  general_discussion text,
  efficiency_score numeric DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT performance_sessions_pkey PRIMARY KEY (id),
  CONSTRAINT performance_sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.performance_tasks (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  session_id uuid NOT NULL,
  task_type text NOT NULL,
  description text NOT NULL,
  status text DEFAULT 'todo'::text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT performance_tasks_pkey PRIMARY KEY (id),
  CONSTRAINT performance_tasks_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.performance_sessions(id)
);
CREATE TABLE public.playbook_assignments (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  playbook_id uuid NOT NULL,
  assignment_type text NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT playbook_assignments_pkey PRIMARY KEY (id),
  CONSTRAINT playbook_assignments_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.business_info(id),
  CONSTRAINT playbook_assignments_playbook_id_fkey FOREIGN KEY (playbook_id) REFERENCES public.playbooks(id)
);
CREATE TABLE public.playbooks (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  playbookname text NOT NULL,
  description text,
  enginetype text NOT NULL CHECK (enginetype = ANY (ARRAY['GROWTH'::text, 'FULFILLMENT'::text, 'INNOVATION'::text])),
  status text NOT NULL CHECK (status = ANY (ARRAY['Backlog'::text, 'In Progress'::text, 'Behind'::text, 'Completed'::text])),
  link text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  department_id uuid,
  content text DEFAULT ''::text,
  CONSTRAINT playbooks_pkey PRIMARY KEY (id),
  CONSTRAINT playbooks_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT playbooks_department_id_fkey FOREIGN KEY (department_id) REFERENCES public.departments(id)
);
CREATE TABLE public.product_error_codes (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  product_id bigint NOT NULL,
  error_code_id bigint NOT NULL,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT product_error_codes_pkey PRIMARY KEY (id),
  CONSTRAINT product_error_codes_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id),
  CONSTRAINT product_error_codes_error_code_id_fkey FOREIGN KEY (error_code_id) REFERENCES public.error_codes(id)
);
CREATE TABLE public.products (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  client_id bigint,
  category character varying CHECK (category::text = ANY (ARRAY['boiler'::character varying, 'ac'::character varying, 'ashp'::character varying, 'battery_storage'::character varying, 'solar'::character varying]::text[])),
  category_ref_id bigint,
  brand_id bigint,
  title character varying NOT NULL,
  subtitle character varying,
  currency character varying DEFAULT 'GBP'::character varying,
  power_rating character varying,
  width character varying,
  height character varying,
  depth character varying,
  image character varying,
  images jsonb DEFAULT '[]'::jsonb,
  features jsonb DEFAULT '[]'::jsonb,
  description text,
  product_specs jsonb DEFAULT '{}'::jsonb,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  embeddings USER-DEFINED,
  content text,
  metadata jsonb,
  CONSTRAINT products_pkey PRIMARY KEY (id)
);
CREATE TABLE public.prompts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  prompt_key text NOT NULL UNIQUE,
  description text NOT NULL,
  prompt_text text NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT prompts_pkey PRIMARY KEY (id)
);
CREATE TABLE public.quarter_planning (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  team_id uuid NOT NULL UNIQUE,
  y1_sales numeric,
  y1_profit numeric,
  target_sales numeric,
  target_profit numeric,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  straight_line_data jsonb DEFAULT '{}'::jsonb,
  actual_data jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT quarter_planning_pkey PRIMARY KEY (id)
);
CREATE TABLE public.quarterly_sprint_canvas (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  revenuegoals jsonb NOT NULL DEFAULT '{"best": "", "good": "", "better": ""}'::jsonb,
  unitgoals ARRAY NOT NULL DEFAULT '{}'::jsonb[],
  revenuebymonth ARRAY NOT NULL DEFAULT '{}'::jsonb[],
  theme text,
  strategicpillars ARRAY NOT NULL DEFAULT '{"","",""}'::text[],
  northstarmetrics ARRAY NOT NULL DEFAULT '{}'::jsonb[],
  keyinitiatives ARRAY NOT NULL DEFAULT '{}'::jsonb[],
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT quarterly_sprint_canvas_pkey PRIMARY KEY (id),
  CONSTRAINT quarterly_sprint_canvas_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.quickbooks_data (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  company_id text NOT NULL,
  company_name text,
  access_token text NOT NULL,
  refresh_token text NOT NULL,
  expires_at timestamp with time zone NOT NULL,
  connected_at timestamp with time zone DEFAULT now(),
  last_sync timestamp with time zone,
  status text DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'expired'::text, 'error'::text])),
  qb_data jsonb DEFAULT '{}'::jsonb,
  current_kpis jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  kpi_history jsonb,
  CONSTRAINT quickbooks_data_pkey PRIMARY KEY (id),
  CONSTRAINT quickbooks_data_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.reviews_cache (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_name text NOT NULL,
  summary_data jsonb NOT NULL,
  last_updated timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT reviews_cache_pkey PRIMARY KEY (id)
);
CREATE TABLE public.service_subcategories (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  team_id uuid NOT NULL,
  service_id uuid NOT NULL,
  subcategory_name text NOT NULL,
  description text,
  ai_generated boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT service_subcategories_pkey PRIMARY KEY (id),
  CONSTRAINT service_subcategories_team_id_fkey FOREIGN KEY (team_id) REFERENCES auth.users(id),
  CONSTRAINT service_subcategories_service_id_fkey FOREIGN KEY (service_id) REFERENCES public.global_services(id)
);
CREATE TABLE public.servicem8_categories (
  uuid uuid NOT NULL,
  user_id uuid NOT NULL,
  name text NOT NULL,
  color text,
  active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT servicem8_categories_pkey PRIMARY KEY (uuid),
  CONSTRAINT servicem8_categories_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.servicem8_companies (
  uuid uuid NOT NULL,
  user_id uuid NOT NULL,
  name text,
  address text,
  billing_address text,
  email text,
  phone text,
  abn_number text,
  is_individual text,
  website text,
  fax_number text,
  badges text,
  payment_terms text,
  active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT servicem8_companies_pkey PRIMARY KEY (uuid),
  CONSTRAINT servicem8_companies_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.servicem8_contacts (
  uuid uuid NOT NULL,
  user_id uuid NOT NULL,
  company_uuid uuid,
  first_name text,
  last_name text,
  email text,
  phone text,
  mobile text,
  type text,
  is_primary_contact text,
  active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT servicem8_contacts_pkey PRIMARY KEY (uuid),
  CONSTRAINT servicem8_contacts_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT fk_contact_company FOREIGN KEY (company_uuid) REFERENCES public.servicem8_companies(uuid)
);
CREATE TABLE public.servicem8_data (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  api_key text,
  connected_at timestamp with time zone DEFAULT now(),
  last_sync_at timestamp with time zone,
  sync_status text DEFAULT 'pending'::text,
  jobs jsonb DEFAULT '[]'::jsonb,
  staff jsonb DEFAULT '[]'::jsonb,
  companies jsonb DEFAULT '[]'::jsonb,
  job_activities jsonb DEFAULT '[]'::jsonb,
  job_materials jsonb DEFAULT '[]'::jsonb,
  error_message text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  access_token text,
  refresh_token text,
  expires_at timestamp with time zone,
  tenant_id text,
  organization_name text,
  scopes text,
  payments jsonb DEFAULT '[]'::jsonb,
  CONSTRAINT servicem8_data_pkey PRIMARY KEY (id),
  CONSTRAINT servicem8_data_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.servicem8_job_activities (
  uuid uuid NOT NULL,
  user_id uuid NOT NULL,
  job_uuid uuid,
  staff_uuid uuid,
  start_date timestamp with time zone,
  end_date timestamp with time zone,
  travel_time_in_seconds integer DEFAULT 0,
  travel_distance_in_meters integer,
  activity_was_scheduled text,
  activity_was_recorded text,
  activity_was_automated text,
  has_been_opened text,
  has_been_opened_timestamp timestamp with time zone,
  active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT servicem8_job_activities_pkey PRIMARY KEY (uuid),
  CONSTRAINT servicem8_job_activities_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT fk_activity_job FOREIGN KEY (job_uuid) REFERENCES public.servicem8_jobs(uuid),
  CONSTRAINT fk_activity_staff FOREIGN KEY (staff_uuid) REFERENCES public.servicem8_staff(uuid)
);
CREATE TABLE public.servicem8_job_contacts (
  uuid uuid NOT NULL,
  user_id uuid NOT NULL,
  job_uuid uuid,
  first_name text,
  last_name text,
  email text,
  phone text,
  mobile text,
  type text,
  active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT servicem8_job_contacts_pkey PRIMARY KEY (uuid),
  CONSTRAINT servicem8_job_contacts_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT fk_job_contact_job FOREIGN KEY (job_uuid) REFERENCES public.servicem8_jobs(uuid)
);
CREATE TABLE public.servicem8_job_payments (
  uuid uuid NOT NULL,
  user_id uuid NOT NULL,
  job_uuid uuid,
  amount numeric DEFAULT 0,
  timestamp timestamp with time zone,
  method text,
  note text,
  actioned_by_uuid uuid,
  is_deposit text,
  active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT servicem8_job_payments_pkey PRIMARY KEY (uuid),
  CONSTRAINT servicem8_job_payments_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT fk_payment_job FOREIGN KEY (job_uuid) REFERENCES public.servicem8_jobs(uuid)
);
CREATE TABLE public.servicem8_jobs (
  uuid uuid NOT NULL,
  user_id uuid NOT NULL,
  job_number text,
  generated_job_id text,
  status text,
  date timestamp with time zone,
  completion_date timestamp with time zone,
  total_invoice_amount numeric DEFAULT 0,
  payment_amount numeric,
  payment_method text,
  payment_received text,
  payment_processed text,
  payment_received_stamp timestamp with time zone,
  payment_processed_stamp timestamp with time zone,
  invoice_sent text,
  invoice_sent_stamp timestamp with time zone,
  ready_to_invoice text,
  ready_to_invoice_stamp timestamp with time zone,
  quote_date timestamp with time zone,
  quote_sent text,
  quote_sent_stamp timestamp with time zone,
  work_order_date timestamp with time zone,
  company_uuid uuid,
  category_uuid uuid,
  created_by_staff_uuid uuid,
  job_address text,
  billing_address text,
  job_description text,
  work_done_description text,
  purchase_order_number text,
  badges text,
  active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT servicem8_jobs_pkey PRIMARY KEY (uuid),
  CONSTRAINT servicem8_jobs_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT fk_job_company FOREIGN KEY (company_uuid) REFERENCES public.servicem8_companies(uuid),
  CONSTRAINT fk_job_category FOREIGN KEY (category_uuid) REFERENCES public.servicem8_categories(uuid),
  CONSTRAINT fk_job_staff FOREIGN KEY (created_by_staff_uuid) REFERENCES public.servicem8_staff(uuid)
);
CREATE TABLE public.servicem8_staff (
  uuid uuid NOT NULL,
  user_id uuid NOT NULL,
  first_name text,
  last_name text,
  email text,
  mobile text,
  job_title text,
  color text,
  status_message text,
  hide_from_schedule text,
  active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT servicem8_staff_pkey PRIMARY KEY (uuid),
  CONSTRAINT servicem8_staff_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.software (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  software text NOT NULL,
  url text,
  description text,
  price_monthly numeric,
  department_id uuid,
  team_id uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  pricing_period text DEFAULT 'monthly'::text CHECK (pricing_period = ANY (ARRAY['monthly'::text, 'yearly'::text, 'custom'::text, 'n/a'::text])),
  CONSTRAINT software_pkey PRIMARY KEY (id),
  CONSTRAINT software_department_id_fkey FOREIGN KEY (department_id) REFERENCES public.departments(id),
  CONSTRAINT software_team_id_fkey FOREIGN KEY (team_id) REFERENCES auth.users(id)
);
CREATE TABLE public.sop_data (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  title character varying NOT NULL,
  content text NOT NULL,
  version integer NOT NULL DEFAULT 1,
  is_current boolean NOT NULL DEFAULT true,
  parent_sop_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  metadata jsonb,
  CONSTRAINT sop_data_pkey PRIMARY KEY (id),
  CONSTRAINT sop_data_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT sop_data_parent_sop_id_fkey FOREIGN KEY (parent_sop_id) REFERENCES public.sop_data(id)
);
CREATE TABLE public.superadmin_analytics_assignments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  superadmin_user_id uuid NOT NULL,
  assigned_user_id uuid NOT NULL,
  property_id text NOT NULL,
  property_name text,
  account_name text,
  assigned_at timestamp with time zone DEFAULT now(),
  is_active boolean DEFAULT true,
  CONSTRAINT superadmin_analytics_assignments_pkey PRIMARY KEY (id),
  CONSTRAINT superadmin_analytics_assignments_superadmin_user_id_fkey FOREIGN KEY (superadmin_user_id) REFERENCES auth.users(id),
  CONSTRAINT superadmin_analytics_assignments_assigned_user_id_fkey FOREIGN KEY (assigned_user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.superadmin_google_analytics_tokens (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  superadmin_user_id uuid NOT NULL UNIQUE,
  access_token text NOT NULL,
  refresh_token text,
  token_type text DEFAULT 'Bearer'::text,
  expires_at timestamp with time zone,
  scope text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT superadmin_google_analytics_tokens_pkey PRIMARY KEY (id),
  CONSTRAINT superadmin_google_analytics_tokens_superadmin_user_id_fkey FOREIGN KEY (superadmin_user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.tasks (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title character varying,
  description text NOT NULL,
  links text,
  task_type character varying NOT NULL DEFAULT 'self'::character varying CHECK (task_type::text = ANY (ARRAY['team'::character varying, 'self'::character varying, 'shared'::character varying]::text[])),
  status character varying NOT NULL DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying, 'in_progress'::character varying, 'completed'::character varying]::text[])),
  priority character varying NOT NULL DEFAULT 'medium'::character varying CHECK (priority::text = ANY (ARRAY['low'::character varying, 'medium'::character varying, 'high'::character varying]::text[])),
  start_date date,
  due_date date,
  assigned_to uuid,
  created_by uuid NOT NULL,
  team_id uuid NOT NULL,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT tasks_pkey PRIMARY KEY (id),
  CONSTRAINT tasks_assigned_to_fkey FOREIGN KEY (assigned_to) REFERENCES auth.users(id),
  CONSTRAINT tasks_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.team_benefit_status (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  team_id uuid NOT NULL,
  benefit_id uuid NOT NULL,
  is_disabled boolean NOT NULL DEFAULT false,
  disabled_by uuid,
  disabled_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT team_benefit_status_pkey PRIMARY KEY (id),
  CONSTRAINT team_benefit_status_team_id_fkey FOREIGN KEY (team_id) REFERENCES auth.users(id),
  CONSTRAINT team_benefit_status_benefit_id_fkey FOREIGN KEY (benefit_id) REFERENCES public.chq_benefits(id),
  CONSTRAINT team_benefit_status_disabled_by_fkey FOREIGN KEY (disabled_by) REFERENCES auth.users(id)
);
CREATE TABLE public.team_leaves (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  leave_type text NOT NULL,
  start_date date NOT NULL,
  end_date date NOT NULL,
  status text NOT NULL DEFAULT 'pending'::text,
  duration_days integer NOT NULL,
  description text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT team_leaves_pkey PRIMARY KEY (id),
  CONSTRAINT team_leaves_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.team_services (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  team_id uuid NOT NULL,
  service_id uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT team_services_pkey PRIMARY KEY (id),
  CONSTRAINT team_services_team_id_fkey FOREIGN KEY (team_id) REFERENCES auth.users(id),
  CONSTRAINT team_services_service_id_fkey FOREIGN KEY (service_id) REFERENCES public.global_services(id)
);
CREATE TABLE public.triage_planner (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  company_info jsonb DEFAULT '{}'::jsonb,
  internal_tasks ARRAY DEFAULT '{}'::jsonb[],
  what_you_do text DEFAULT ''::text,
  who_you_serve text DEFAULT ''::text,
  what_is_right ARRAY DEFAULT '{}'::jsonb[],
  what_is_wrong ARRAY DEFAULT '{}'::jsonb[],
  what_is_missing ARRAY DEFAULT '{}'::jsonb[],
  what_is_confusing ARRAY DEFAULT '{}'::jsonb[],
  notes text DEFAULT ''::text,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT triage_planner_pkey PRIMARY KEY (id),
  CONSTRAINT triage_planner_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.unified_integrations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  integration_type text NOT NULL CHECK (integration_type = ANY (ARRAY['quickbooks'::text, 'xero'::text, 'servicem8'::text, 'google_analytics'::text])),
  connection_id text,
  connection_name text,
  access_token text,
  refresh_token text,
  expires_at timestamp with time zone,
  property_id text,
  connected_at timestamp with time zone DEFAULT now(),
  last_sync_at timestamp with time zone,
  sync_status text DEFAULT 'pending'::text CHECK (sync_status = ANY (ARRAY['pending'::text, 'syncing'::text, 'completed'::text, 'error'::text])),
  status text DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'expired'::text, 'error'::text, 'disconnected'::text])),
  error_message text,
  quickbooks_data jsonb DEFAULT '{}'::jsonb,
  xero_data jsonb DEFAULT '{}'::jsonb,
  servicem8_data jsonb DEFAULT '{}'::jsonb,
  google_analytics_data jsonb DEFAULT '{}'::jsonb,
  quickbooks_kpis jsonb DEFAULT '{}'::jsonb,
  xero_kpis jsonb DEFAULT '{}'::jsonb,
  servicem8_kpis jsonb DEFAULT '{}'::jsonb,
  google_analytics_kpis jsonb DEFAULT '{}'::jsonb,
  quickbooks_history jsonb DEFAULT '{}'::jsonb,
  xero_history jsonb DEFAULT '{}'::jsonb,
  servicem8_history jsonb DEFAULT '{}'::jsonb,
  google_analytics_history jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT unified_integrations_pkey PRIMARY KEY (id),
  CONSTRAINT unified_integrations_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.user_benefit_claims (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  benefit_id uuid NOT NULL,
  is_claimed boolean NOT NULL DEFAULT false,
  claimed_date timestamp with time zone,
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT user_benefit_claims_pkey PRIMARY KEY (id),
  CONSTRAINT user_benefit_claims_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT user_benefit_claims_benefit_id_fkey FOREIGN KEY (benefit_id) REFERENCES public.chq_benefits(id)
);
CREATE TABLE public.user_checklist_claims (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  checklist_id uuid NOT NULL,
  is_completed boolean NOT NULL DEFAULT false,
  completion_date timestamp with time zone,
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT user_checklist_claims_pkey PRIMARY KEY (id),
  CONSTRAINT user_checklist_claims_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT user_checklist_claims_checklist_id_fkey FOREIGN KEY (checklist_id) REFERENCES public.chq_checklist(id)
);
CREATE TABLE public.user_course_enrollment (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  course_id uuid,
  enrolled_at timestamp with time zone DEFAULT now(),
  is_completed boolean DEFAULT false,
  progress_percentage numeric DEFAULT 0.00,
  completed_at timestamp with time zone,
  last_accessed_at timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  last_accessed_lesson_id uuid,
  CONSTRAINT user_course_enrollment_pkey PRIMARY KEY (id),
  CONSTRAINT user_course_enrollment_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT user_course_enrollment_course_id_fkey FOREIGN KEY (course_id) REFERENCES public.courses(id),
  CONSTRAINT user_course_enrollment_last_accessed_lesson_id_fkey FOREIGN KEY (last_accessed_lesson_id) REFERENCES public.course_lessons(id)
);
CREATE TABLE public.user_course_progress (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  lesson_id uuid,
  is_completed boolean DEFAULT false,
  progress_percentage numeric DEFAULT 0.00,
  watch_time_seconds integer DEFAULT 0,
  completed_at timestamp with time zone,
  last_watched_at timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  team_id uuid NOT NULL,
  CONSTRAINT user_course_progress_pkey PRIMARY KEY (id),
  CONSTRAINT user_course_progress_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT user_course_progress_lesson_id_fkey FOREIGN KEY (lesson_id) REFERENCES public.course_lessons(id),
  CONSTRAINT user_course_progress_team_id_fkey FOREIGN KEY (team_id) REFERENCES auth.users(id)
);
CREATE TABLE public.user_module_progress (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  module_id uuid,
  is_completed boolean DEFAULT false,
  progress_percentage numeric DEFAULT 0.00,
  completed_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  team_id uuid NOT NULL,
  CONSTRAINT user_module_progress_pkey PRIMARY KEY (id),
  CONSTRAINT user_module_progress_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT user_module_progress_module_id_fkey FOREIGN KEY (module_id) REFERENCES public.course_modules(id),
  CONSTRAINT user_module_progress_team_id_fkey FOREIGN KEY (team_id) REFERENCES auth.users(id)
);
CREATE TABLE public.user_points (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL UNIQUE,
  total_points integer DEFAULT 0,
  level integer DEFAULT 1,
  current_streak integer DEFAULT 0,
  longest_streak integer DEFAULT 0,
  last_activity_date date,
  weekly_points integer DEFAULT 0,
  monthly_points integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_points_pkey PRIMARY KEY (id),
  CONSTRAINT user_points_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.user_timeline_claims (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  timeline_id uuid NOT NULL,
  is_completed boolean NOT NULL DEFAULT false,
  completion_date timestamp with time zone,
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT user_timeline_claims_pkey PRIMARY KEY (id),
  CONSTRAINT user_timeline_claims_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT user_timeline_claims_timeline_id_fkey FOREIGN KEY (timeline_id) REFERENCES public.chq_timeline(id)
);
CREATE TABLE public.xero_data (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  tenant_id text NOT NULL,
  organization_name text,
  access_token text NOT NULL,
  refresh_token text NOT NULL,
  expires_at timestamp with time zone NOT NULL,
  connected_at timestamp with time zone DEFAULT now(),
  last_sync_at timestamp with time zone,
  sync_status text DEFAULT 'pending'::text CHECK (sync_status = ANY (ARRAY['pending'::text, 'syncing'::text, 'completed'::text, 'error'::text])),
  error_message text,
  invoices jsonb DEFAULT '[]'::jsonb,
  contacts jsonb DEFAULT '[]'::jsonb,
  accounts jsonb DEFAULT '[]'::jsonb,
  bank_transactions jsonb DEFAULT '[]'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT xero_data_pkey PRIMARY KEY (id),
  CONSTRAINT xero_data_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.xero_kpis (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  tenant_id text NOT NULL,
  period text NOT NULL,
  period_start date NOT NULL,
  period_end date NOT NULL,
  kpis jsonb NOT NULL DEFAULT '[]'::jsonb,
  calculated_at timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT xero_kpis_pkey PRIMARY KEY (id),
  CONSTRAINT xero_kpis_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);