-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Jan 08, 2026 at 07:14 AM
-- Server version: 10.4.32-MariaDB
-- PHP Version: 8.2.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `quote_builder_pro`
--

-- --------------------------------------------------------

--
-- Table structure for table `tbl_ashp_package_detail`
--

CREATE TABLE `tbl_ashp_package_detail` (
  `id` int(11) NOT NULL,
  `client_id` int(11) DEFAULT NULL,
  `ashp_detail` longtext DEFAULT NULL,
  `radiator_detail` longtext DEFAULT NULL,
  `cylinder_detail` longtext DEFAULT NULL,
  `package_price` varchar(265) DEFAULT NULL,
  `ashp_size` varchar(50) DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT current_timestamp(),
  `updated_at` datetime NOT NULL DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

--
-- Dumping data for table `tbl_ashp_package_detail`
--

INSERT INTO `tbl_ashp_package_detail` (`id`, `client_id`, `ashp_detail`, `radiator_detail`, `cylinder_detail`, `package_price`, `ashp_size`, `created_at`, `updated_at`) VALUES
(2, 241, '{\"brand_name\":\"Mitsubishi\",\"ashp_title\":\"5kW R32 1Ph Mono ASHP Outdoor Unit \",\"ashp_description\":\"The new stylish compact single fan outdoor monobloc air source heat pump unit utilises advance technologies and R32 refrigerant to deliver improved efficiencies. Designed to satisfy smaller heat demand domestic premises, the market leading low noise levels virtually eliminate the need for planning permission and maximises installation options.\",\"ashp_properties\":[\"A+++ high efficiency system.\",\"  Low noise levels.\",\"  Maintain full heating capacity at low temperatures.\",\"  Zero carbon solution.\",\"  MELCloud Enabled.\"],\"ashp_warranty\":\"7\",\"ashp_power\":\"5\",\"ashp_noise_level\":\"47\",\"height\":\"950\",\"width\":\"943\",\"depth\":\"330\",\"image_path\":\"https:\\/\\/ashp-images.b-cdn.net\\/MItsubushi_EcodanR32.png\"}', '{\"title\":\"ASHP Radiator B\",\"size\":\"8 RADS\",\"imagePath\":\"https:\\/\\/ashp-images.b-cdn.net\\/MItsubushi_EcodanR32.png\",\"properties\":[\"Danfoss RAS-C2 Thermostatic Radiator Valve and Lock Shield Pack.\",\"Pipe, Fittings & Sundry Items.\"]}', '{\"brand\":\"1\",\"title\":\"Mitsubishi Standard Pre-Plumbed Cylinder 170 Litres\",\"size\":\"170\",\"imagePath\":\"https:\\/\\/ashp-images.b-cdn.net\\/Cylinder\\/Ecodan_170Litre.png\",\"properties\":[\"Unvented plug & play packaged DHW cylinder.\",\"Efficient & rapid heating.\",\"Flexible 2-zone space heating control.\"]}', '7893', 'two', '2025-03-28 10:12:33', '2025-03-28 10:12:33'),
(12, 283, '{\"brand_name\":\"Mitsubishi\",\"ashp_title\":\"5kW R32 1Ph Mono ASHP Outdoor Unit \",\"ashp_description\":\"The new stylish compact single fan outdoor monobloc air source heat pump unit utilises advance technologies and R32 refrigerant to deliver improved efficiencies. Designed to satisfy smaller heat demand domestic premises, the market leading low noise levels virtually eliminate the need for planning permission and maximises installation options.\",\"ashp_properties\":[\"A+++ high efficiency system.\",\"  Low noise levels.\",\"  Maintain full heating capacity at low temperatures.\",\"  Zero carbon solution.\",\"  MELCloud Enabled.\"],\"ashp_warranty\":\"7\",\"ashp_power\":\"5\",\"ashp_noise_level\":\"47\",\"height\":\"950\",\"width\":\"943\",\"depth\":\"330\",\"image_path\":\"https:\\/\\/ashp-images.b-cdn.net\\/MItsubushi_EcodanR32.png\"}', NULL, NULL, '2000', 'two', '2025-06-19 08:32:08', '2025-06-20 08:13:06'),
(13, 283, '{\"brand_name\":\"Mitsubishi\",\"ashp_title\":\"Mitsubishi Electric R32 Mono ASHP 3 bed\",\"ashp_description\":\"\\\"Mitsubishi Heat Pump Controller\\r\\nWireless Room Thermostat\\r\\nMELcloud (app control)\\r\\nRubber anti-vibration Feet\\r\\nFlexible Heat pump hoses\\r\\nDischarge Vessel\\r\\nHeating Expansion Vessel with Kit\\r\\nSystem Volumiser\\r\\nMagnetic & particle Filter\\r\\nBypass Valve\\r\\nAntifreeze\\r\\nPipe, Fittings, Electrical & Sundry Items\\r\\nMCS Documentation\\\"\",\"ashp_properties\":[\"Mitsubishi Heat Pump Controller \",\"  Wireless Room Thermostat \",\"  MELcloud (app control) \",\"  Rubber anti-vibration Feet \",\"  Flexible Heat pump hoses \",\"  Discharge Vessel \",\"  Heating Expansion Vessel with Kit \",\"  System Volumiser \",\"  Magnetic & particle Filter \",\"  Bypass Valve \",\"  Antifreeze \",\"  Pipe, Fittings, Electrical & Sundry Items \",\"  MCS Documentation\"],\"ashp_warranty\":\"7\",\"ashp_power\":\"8.5\",\"ashp_noise_level\":\"45\",\"height\":\"1020\",\"width\":\"1050\",\"depth\":\"480\",\"image_path\":\"https:\\/\\/ashp.quotebuilderpro.com\\/public\\/static_image\\/Mitsubishi%20Electric%20R32%20Mono%20ASHP.png\"}', NULL, NULL, '100', 'two', '2025-06-19 12:59:55', '2025-06-19 12:59:55'),
(14, 283, '{\"brand_name\":\"Vaillant\",\"ashp_title\":\"Vaillant Arotherm +\",\"ashp_description\":\"\\\"Wireless Sensocomfort Controller\\r\\nMyVaillant connect internet gateway (app control)\\r\\nRubber anti-biration Feet\\r\\nFlexible Heat pump hoses\\r\\nDischarge Vessel\\r\\nHeating Expansion Vessel with Kit\\r\\nSystem volumiser\\r\\nMagnetic & particle Filter\\r\\nBypass Valve\\r\\nAntifreeze\\r\\nPipe, Fittings, Electrical & Sundry Items\\r\\nMCS Documentation\\\"\",\"ashp_properties\":[\"Wireless Sensocomfort Controller \",\"    MyVaillant connect internet gateway (app control) \",\"    Rubber anti-biration Feet \",\"    Flexible Heat pump hoses \",\"    Discharge Vessel \",\"    Heating Expansion Vessel with Kit \",\"    System volumiser \",\"    Magnetic & particle Filter \",\"    Bypass Valve \",\"    Antifreeze \",\"    Pipe, Fittings, Electrical & Sundry Items \",\"    MCS Documentation\"],\"ashp_warranty\":\"7\",\"ashp_power\":\"7\",\"ashp_noise_level\":\"55\",\"height\":\"1000\",\"width\":\"1001\",\"depth\":\"1002\",\"image_path\":\"https:\\/\\/ashp.quotebuilderpro.com\\/public\\/static_image\\/Vaillant%20Arotherm.png\"}', NULL, NULL, '5001.00', 'two', '2025-06-24 12:34:45', '2025-06-25 13:21:41'),
(15, 283, '{\"brand_name\":\"Mitsubishi\",\"ashp_title\":\"5kW R32 1Ph Mono ASHP Outdoor Unit \",\"ashp_description\":\"The new stylish compact single fan outdoor monobloc air source heat pump unit utilises advance technologies and R32 refrigerant to deliver improved efficiencies. Designed to satisfy smaller heat demand domestic premises, the market leading low noise levels virtually eliminate the need for planning permission and maximises installation options.\",\"ashp_properties\":[\"A+++ high efficiency system.\",\"  Low noise levels.\",\"  Maintain full heating capacity at low temperatures.\",\"  Zero carbon solution.\",\"  MELCloud Enabled.\"],\"ashp_warranty\":\"7\",\"ashp_power\":\"5\",\"ashp_noise_level\":\"47\",\"height\":\"950\",\"width\":\"943\",\"depth\":\"330\",\"image_path\":\"https:\\/\\/ashp-images.b-cdn.net\\/MItsubushi_EcodanR32.png\"}', '{\"title\":\"ASHP Radiator D\",\"size\":\"12 RADS\",\"imagePath\":\"https:\\/\\/ashp-images.b-cdn.net\\/MItsubushi_EcodanR32.png\",\"properties\":[\"Danfoss RAS-C2 Thermostatic Radiator Valve and Lock Shield Pack.\",\"Pipe, Fittings & Sundry Items.\"]}', NULL, '5998.99', 'two', '2025-06-25 07:25:45', '2025-06-25 07:25:45'),
(16, 283, '{\"brand_name\":\"Mitsubishi\",\"ashp_title\":\"5kW R32 1Ph Mono ASHP Outdoor Unit \",\"ashp_description\":\"The new stylish compact single fan outdoor monobloc air source heat pump unit utilises advance technologies and R32 refrigerant to deliver improved efficiencies. Designed to satisfy smaller heat demand domestic premises, the market leading low noise levels virtually eliminate the need for planning permission and maximises installation options.\",\"ashp_properties\":[\"A+++ high efficiency system.\",\"  Low noise levels.\",\"  Maintain full heating capacity at low temperatures.\",\"  Zero carbon solution.\",\"  MELCloud Enabled.\"],\"ashp_warranty\":\"7\",\"ashp_power\":\"5\",\"ashp_noise_level\":\"47\",\"height\":\"950\",\"width\":\"943\",\"depth\":\"330\",\"image_path\":\"https:\\/\\/ashp-images.b-cdn.net\\/MItsubushi_EcodanR32.png\"}', NULL, NULL, '11234.89', 'three', '2025-07-15 06:45:14', '2025-07-15 06:45:14'),
(17, 283, '{\"brand_name\":\"Mitsubishi\",\"ashp_title\":\"Mitsubishi Electric R32 Mono ASHP 4 bed\",\"ashp_description\":\"Mitsubishi Heat Pump Controller\\r\\nWireless Room Thermostat\\r\\nMELcloud (app control)\\r\\nRubber anti-vibration Feet\\r\\nFlexible Heat pump hoses\\r\\nDischarge Vessel\\r\\nHeating Expansion Vessel with Kit\\r\\nSystem Volumiser\\r\\nMagnetic & particle Filter\\r\\nBypass Valve\\r\\nAntifreeze\\r\\nPipe, Fittings, Electrical & Sundry Items\\r\\nMCS Documentation\",\"ashp_properties\":[\"Mitsubishi Heat Pump Controller \",\"  Wireless Room Thermostat \",\"  MELcloud (app control) \",\"  Rubber anti-vibration Feet \",\"  Flexible Heat pump hoses \",\"  Discharge Vessel \",\"  Heating Expansion Vessel with Kit \",\"  System Volumiser \",\"  Magnetic & particle Filter \",\"  Bypass Valve \",\"  Antifreeze \",\"  Pipe, Fittings, Electrical & Sundry Items \",\"  MCS Documentation\"],\"ashp_warranty\":\"7\",\"ashp_power\":\"11.2\",\"ashp_noise_level\":\"47\",\"height\":\"1020\",\"width\":\"1050\",\"depth\":\"480\",\"image_path\":\"https:\\/\\/ashp.quotebuilderpro.com\\/public\\/static_image\\/Mitsubishi%20Electric%20R32%20Mono%20ASHP.png\"}', NULL, NULL, '8685', 'four', '2025-07-15 06:45:26', '2025-07-15 06:45:26'),
(18, 283, '{\"brand_name\":\"Mitsubishi\",\"ashp_title\":\"Mitsubishi Electric R32 Mono ASHP 5 bed\",\"ashp_description\":\"Mitsubishi Heat Pump Controller\\r\\nWireless Room Thermostat\\r\\nMELcloud (app control)\\r\\nRubber anti-vibration Feet\\r\\nFlexible Heat pump hoses\\r\\nDischarge Vessel\\r\\nHeating Expansion Vessel with Kit\\r\\nSystem Volumiser\\r\\nMagnetic & particle Filter\\r\\nBypass Valve\\r\\nAntifreeze\\r\\nPipe, Fittings, Electrical & Sundry Items\\r\\nMCS Documentation\",\"ashp_properties\":[\"\\\"Mitsubishi Heat Pump Controller \",\"  Wireless Room Thermostat \",\"  MELcloud (app control) \",\"  Rubber anti-vibration Feet \",\"  Flexible Heat pump hoses \",\"  Discharge Vessel \",\"  Heating Expansion Vessel with Kit \",\"  System Volumiser \",\"  Magnetic & particle Filter \",\"  Bypass Valve \",\"  Antifreeze \",\"  Pipe, Fittings, Electrical & Sundry Items \",\"  MCS Documentation\"],\"ashp_warranty\":\"7\",\"ashp_power\":\"14\",\"ashp_noise_level\":\"53\",\"height\":\"1020\",\"width\":\"1350\",\"depth\":\"360\",\"image_path\":\"https:\\/\\/ashp.quotebuilderpro.com\\/public\\/static_image\\/Mitsubishi%20Electric%20R32%20Mono%20ASHP.png\"}', NULL, NULL, '757878', 'five', '2025-07-15 06:45:36', '2025-07-15 06:45:36'),
(21, 288, '{\"brand_name\":\"Vaillant\",\"ashp_title\":\"Vaillant Arotherm +\",\"ashp_description\":\"\\\"Wireless Sensocomfort Controller\\r\\nMyVaillant connect internet gateway (app control)\\r\\nRubber anti-biration Feet\\r\\nFlexible Heat pump hoses\\r\\nDischarge Vessel\\r\\nHeating Expansion Vessel with Kit\\r\\nSystem volumiser\\r\\nMagnetic & particle Filter\\r\\nBypass Valve\\r\\nAntifreeze\\r\\nPipe, Fittings, Electrical & Sundry Items\\r\\nMCS Documentation\\\"\",\"ashp_properties\":[\"Wireless Sensocomfort Controller \",\"     MyVaillant connect internet gateway (app control) \",\"     Rubber anti-biration Feet \",\"     Flexible Heat pump hoses \",\"     Discharge Vessel \",\"     Heating Expansion Vessel with Kit \",\"     System volumiser \",\"     Magnetic & particle Filter \",\"     Bypass Valve \",\"     Antifreeze \",\"     Pipe, Fittings, Electrical & Sundry Items \",\"     MCS Documentation\"],\"ashp_warranty\":\"7\",\"ashp_power\":\"7\",\"ashp_noise_level\":\"55\",\"height\":\"1100\",\"width\":\"965\",\"depth\":\"450\",\"image_path\":\"https:\\/\\/ashp-images.b-cdn.net\\/Vaillant_Arotherm%2B.png\"}', NULL, NULL, '3560.00', 'four', '2025-07-15 11:18:50', '2025-07-15 11:18:50'),
(22, 288, '{\"brand_name\":\"Mitsubishi\",\"ashp_title\":\"5kW R32 1Ph Mono ASHP Outdoor Unit \",\"ashp_description\":\"The new stylish compact single fan outdoor monobloc air source heat pump unit utilises advance technologies and R32 refrigerant to deliver improved efficiencies. Designed to satisfy smaller heat demand domestic premises, the market leading low noise levels virtually eliminate the need for planning permission and maximises installation options.\",\"ashp_properties\":[\"A+++ high efficiency system.\",\"  Low noise levels.\",\"  Maintain full heating capacity at low temperatures.\",\"  Zero carbon solution.\",\"  MELCloud Enabled.\"],\"ashp_warranty\":\"7\",\"ashp_power\":\"5\",\"ashp_noise_level\":\"47\",\"height\":\"950\",\"width\":\"943\",\"depth\":\"330\",\"image_path\":\"https:\\/\\/ashp-images.b-cdn.net\\/MItsubushi_EcodanR32.png\"}', '{\"title\":\"\",\"size\":\"8 RADS\",\"imagePath\":\"\",\"properties\":[]}', '{\"brand\":\"3\",\"title\":\"\",\"size\":\"210\",\"imagePath\":\"\",\"properties\":[]}', '3000.00', 'five', '2025-07-15 11:19:07', '2025-07-22 05:36:20'),
(23, 283, '{\"brand_name\":\"Mitsubishi\",\"ashp_title\":\"5kW R32 1Ph Mono ASHP Outdoor Unit \",\"ashp_description\":\"The new stylish compact single fan outdoor monobloc air source heat pump unit utilises advance technologies and R32 refrigerant to deliver improved efficiencies. Designed to satisfy smaller heat demand domestic premises, the market leading low noise levels virtually eliminate the need for planning permission and maximises installation options.\",\"ashp_properties\":[\"A+++ high efficiency system.\",\"  Low noise levels.\",\"  Maintain full heating capacity at low temperatures.\",\"  Zero carbon solution.\",\"  MELCloud Enabled.\"],\"ashp_warranty\":\"7\",\"ashp_power\":\"5\",\"ashp_noise_level\":\"47\",\"height\":\"950\",\"width\":\"943\",\"depth\":\"330\",\"image_path\":\"https:\\/\\/ashp-images.b-cdn.net\\/MItsubushi_EcodanR32.png\"}', NULL, NULL, '100', 'one', '2025-07-15 13:04:46', '2025-07-15 13:04:46'),
(24, 288, '{\"brand_name\":\"Mitsubishi\",\"ashp_title\":\"5kW R32 1Ph Mono ASHP Outdoor Unit \",\"ashp_description\":\"The new stylish compact single fan outdoor monobloc air source heat pump unit utilises advance technologies and R32 refrigerant to deliver improved efficiencies. Designed to satisfy smaller heat demand domestic premises, the market leading low noise levels virtually eliminate the need for planning permission and maximises installation options.\",\"ashp_properties\":[\"A+++ high efficiency system.\",\"  Low noise levels.\",\"  Maintain full heating capacity at low temperatures.\",\"  Zero carbon solution.\",\"  MELCloud Enabled.\"],\"ashp_warranty\":\"7\",\"ashp_power\":\"5\",\"ashp_noise_level\":\"47\",\"height\":\"950\",\"width\":\"943\",\"depth\":\"330\",\"image_path\":\"https:\\/\\/ashp-images.b-cdn.net\\/MItsubushi_EcodanR32.png\"}', NULL, NULL, '20000', 'two', '2025-07-18 10:32:45', '2025-07-18 10:32:45'),
(30, 288, '{\"brand_name\":\"Mitsubishi\",\"ashp_title\":\"5kW R32 1Ph Mono ASHP Outdoor Unit \",\"ashp_description\":\"The new stylish compact single fan outdoor monobloc air source heat pump unit utilises advance technologies and R32 refrigerant to deliver improved efficiencies. Designed to satisfy smaller heat demand domestic premises, the market leading low noise levels virtually eliminate the need for planning permission and maximises installation options.\",\"ashp_properties\":[\"A+++ high efficiency system.\",\"  Low noise levels.\",\"  Maintain full heating capacity at low temperatures.\",\"  Zero carbon solution.\",\"  MELCloud Enabled.\"],\"ashp_warranty\":\"7\",\"ashp_power\":\"5\",\"ashp_noise_level\":\"47\",\"height\":\"950\",\"width\":\"943\",\"depth\":\"330\",\"image_path\":\"https:\\/\\/ashp-images.b-cdn.net\\/MItsubushi_EcodanR32.png\"}', NULL, NULL, '10000.00', 'one', '2025-10-08 08:11:14', '2025-10-08 08:11:14'),
(31, 288, '{\"brand_name\":\"Mitsubishi\",\"ashp_title\":\"5kW R32 1Ph Mono ASHP Outdoor Unit \",\"ashp_description\":\"The new stylish compact single fan outdoor monobloc air source heat pump unit utilises advance technologies and R32 refrigerant to deliver improved efficiencies. Designed to satisfy smaller heat demand domestic premises, the market leading low noise levels virtually eliminate the need for planning permission and maximises installation options.\",\"ashp_properties\":[\"A+++ high efficiency system.\",\"  Low noise levels.\",\"  Maintain full heating capacity at low temperatures.\",\"  Zero carbon solution.\",\"  MELCloud Enabled.\"],\"ashp_warranty\":\"7\",\"ashp_power\":\"5\",\"ashp_noise_level\":\"47\",\"height\":\"950\",\"width\":\"943\",\"depth\":\"330\",\"image_path\":\"https:\\/\\/ashp-images.b-cdn.net\\/MItsubushi_EcodanR32.png\"}', NULL, NULL, '11000.00', 'five+', '2025-10-08 08:11:48', '2025-10-08 08:11:48'),
(32, 288, '{\"brand_name\":\"Vaillant\",\"ashp_title\":\"Vaillant Arotherm +\",\"ashp_description\":\"\\\"Wireless Sensocomfort Controller\\r\\nMyVaillant connect internet gateway (app control)\\r\\nRubber anti-biration Feet\\r\\nFlexible Heat pump hoses\\r\\nDischarge Vessel\\r\\nHeating Expansion Vessel with Kit\\r\\nSystem volumiser\\r\\nMagnetic & particle Filter\\r\\nBypass Valve\\r\\nAntifreeze\\r\\nPipe, Fittings, Electrical & Sundry Items\\r\\nMCS Documentation\\\"\",\"ashp_properties\":[\"Wireless Sensocomfort Controller \",\"     MyVaillant connect internet gateway (app control) \",\"     Rubber anti-biration Feet \",\"     Flexible Heat pump hoses \",\"     Discharge Vessel \",\"     Heating Expansion Vessel with Kit \",\"     System volumiser \",\"     Magnetic & particle Filter \",\"     Bypass Valve \",\"     Antifreeze \",\"     Pipe, Fittings, Electrical & Sundry Items \",\"     MCS Documentation\"],\"ashp_warranty\":\"7\",\"ashp_power\":\"7\",\"ashp_noise_level\":\"55\",\"height\":\"1100\",\"width\":\"965\",\"depth\":\"450\",\"image_path\":\"https:\\/\\/ashp-images.b-cdn.net\\/Vaillant_Arotherm%2B.png\"}', NULL, NULL, '8000.00', 'three', '2025-10-08 12:24:28', '2025-10-08 12:24:28');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `tbl_ashp_package_detail`
--
ALTER TABLE `tbl_ashp_package_detail`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `tbl_ashp_package_detail`
--
ALTER TABLE `tbl_ashp_package_detail`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=33;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
