-- Create service_subcategories table to store team-specific subcategories
-- These subcategories are AI-generated based on service details and company onboarding data
-- Each subcategory is specific enough to create targeted growth and fulfillment engines

CREATE TABLE IF NOT EXISTS public.service_subcategories (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  team_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  service_id UUID NOT NULL REFERENCES public.global_services(id) ON DELETE CASCADE,
  subcategory_name TEXT NOT NULL,
  description TEXT,
  ai_generated BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT service_subcategories_unique UNIQUE (team_id, service_id, subcategory_name)
);

-- Create indexes for better query performance
CREATE INDEX IF NOT EXISTS idx_service_subcategories_team_id ON public.service_subcategories(team_id);
CREATE INDEX IF NOT EXISTS idx_service_subcategories_service_id ON public.service_subcategories(service_id);
CREATE INDEX IF NOT EXISTS idx_service_subcategories_team_service ON public.service_subcategories(team_id, service_id);

-- Create trigger for updated_at
CREATE TRIGGER update_service_subcategories_updated_at BEFORE UPDATE ON public.service_subcategories
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- Add comments for documentation
COMMENT ON TABLE public.service_subcategories IS 'Team-specific service subcategories generated from AI analysis. Each subcategory is specific enough to create targeted growth and fulfillment engines.';
COMMENT ON COLUMN public.service_subcategories.team_id IS 'References the team (auth.users.id)';
COMMENT ON COLUMN public.service_subcategories.service_id IS 'References the global service (e.g., Electrical, Plumbing)';
COMMENT ON COLUMN public.service_subcategories.subcategory_name IS 'Specific subcategory name (e.g., Safety Certificate Inspections, Residential Rewiring)';
COMMENT ON COLUMN public.service_subcategories.description IS 'Description of what this subcategory entails';
COMMENT ON COLUMN public.service_subcategories.ai_generated IS 'Whether this subcategory was generated by AI or manually added';

-- Add subcategory_id column to machines table
ALTER TABLE public.machines 
ADD COLUMN IF NOT EXISTS subcategory_id UUID REFERENCES public.service_subcategories(id) ON DELETE SET NULL;

-- Create index for performance
CREATE INDEX IF NOT EXISTS idx_machines_subcategory_id ON public.machines(subcategory_id);

-- Add comment for documentation
COMMENT ON COLUMN public.machines.subcategory_id IS 'Links machine to a specific subcategory. NULL for backward compatibility with existing machines.';

-- Note: We'll update the unique constraint in a separate migration after handling existing data
